services:

  mariadb:
    container_name: mariadb-container
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: nutn@password
      MARIADB_DATABASE: nutn
      MARIADB_USER: nutn
      MARIADB_PASSWORD: nutn@password
    
  python:
    container_name: python-container
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app  # 把當前專案目錄掛載進容器的 /app
    working_dir: /app
    command: tail -f /dev/null # 讓容器保持開啟，使得可以使用此服務跑一些 python 腳本
